"""add relationship nextlevelpoints

Revision ID: 0050b0d7db96
Revises: 8bf9bab8a03b
Create Date: 2025-06-05 00:49:01.662314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0050b0d7db96'
down_revision: Union[str, None] = '8bf9bab8a03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('next_level_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'next_level_points')
    # ### end Alembic commands ###
