"""change column name relationship

Revision ID: 14a81a8f28c7
Revises: 8bf9bab8a03b
Create Date: 2025-06-04 11:36:34.746421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14a81a8f28c7'
down_revision: Union[str, None] = '8bf9bab8a03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_achivements_id', table_name='user_achivements')
    op.drop_table('user_achivements')
    op.drop_index('ix_achivements_id', table_name='achivements')
    op.drop_table('achivements')
    op.add_column('relationships', sa.Column('next_level_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'next_level_points')
    op.create_table('achivements',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('achivements_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('icon_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='achivements_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_achivements_id', 'achivements', ['id'], unique=False)
    op.create_table('user_achivements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('achivement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_unlocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['achivement_id'], ['achivements.id'], name='user_achivements_achivement_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_achivements_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_achivements_pkey')
    )
    op.create_index('ix_user_achivements_id', 'user_achivements', ['id'], unique=False)
    # ### end Alembic commands ###
