"""change character table add gender cover image list

Revision ID: 59681a5463f4
Revises: 4c1c9a383d7c
Create Date: 2025-06-02 05:34:47.322149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59681a5463f4'
down_revision: Union[str, None] = '4c1c9a383d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.add_column('characters', sa.Column('gender', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('personality', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('characters', sa.Column('hobbies', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('characters', sa.Column('specialties', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'specialties')
    op.drop_column('characters', 'hobbies')
    op.drop_column('characters', 'personality')
    op.drop_column('characters', 'gender')
    op.drop_column('characters', 'cover_image_url')
    # ### end Alembic commands ###
