"""create character nfc table

Revision ID: d3435b0ad252
Revises: 0050b0d7db96
Create Date: 2025-06-10 12:26:30.484426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3435b0ad252'
down_revision: Union[str, None] = '0050b0d7db96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_nfc_uuids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('nfc_uuid', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_nfc_uuids_id'), 'character_nfc_uuids', ['id'], unique=False)
    op.create_index(op.f('ix_character_nfc_uuids_nfc_uuid'), 'character_nfc_uuids', ['nfc_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_nfc_uuids_nfc_uuid'), table_name='character_nfc_uuids')
    op.drop_index(op.f('ix_character_nfc_uuids_id'), table_name='character_nfc_uuids')
    op.drop_table('character_nfc_uuids')
    # ### end Alembic commands ###
