"""create level thresholds table

Revision ID: e765d9da8c50
Revises: 95147e92119f
Create Date: 2025-06-02 17:24:58.434051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e765d9da8c50'
down_revision: Union[str, None] = '95147e92119f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('trust_level_id', sa.Integer(), nullable=False),
    sa.Column('required_points', sa.Integer(), nullable=True),
    sa.Column('required_conversations', sa.Integer(), nullable=True),
    sa.Column('required_days_from_first', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['trust_level_id'], ['trust_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_thresholds_id'), 'level_thresholds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_level_thresholds_id'), table_name='level_thresholds')
    op.drop_table('level_thresholds')
    # ### end Alembic commands ###
