apiVersion: v1
kind: Service
metadata:
  name: ht-sb-backend-service
  namespace: ht-sb
spec:
  selector:
    app: ht-sb-backend
  ports:
  - port: 3006
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ht-sb
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  type: ClusterIP